 ### Register User
POST http://localhost:8000/register HTTP/1.1
content-Type: application/json

{
  "username": "abc",
  "password": "1234567",
  "email": "rethanya318@gmail.com",
  "name": "Rethanya"
}

### LOGIN

POST http://localhost:8000/login HTTP/1.1
content-Type: application/json

{
"email": "rethanya318@gmail.com",
"password": "1234567"
}

### LOGIN

POST http://localhost:8000/get_user_and_profile HTTP/1.1
content-Type: application/json

{
  "token": "4b97228a574b3625ca88fcab5c138af9cec775e4413c7860e7630f98b0c92802"
}
 

### update profile data
POST http://localhost:8000/update_profile_data HTTP/1.1
content-Type: application/json

 {
  "token": "68ed16a4674566d9e216a003c9a101e360ea69df40e93a53d2f1e54c30a2a3b7",
  "profile": {
    "_id": "686d35b307d9f0caef8ede3c",
    "userId": "686d35b207d9f0caef8ede3a",
    "bio": "",
    "currentPost": "CID",
    "pastWork": [
      {
        "company": "microsoft",
        "position": "CTO",
        "years": "23"
      }
    ],
    "education": [
      {
        "school": "SNS",
        "Salary": "34",
        "years": "23"
      }
    ],
    "__v": 0
  }
}


GET http://localhost:8000/get_all_users  
 
 